package com.jovan.erp_v1.enumeration;


public enum PermissionResourceType {

	// SKLADISTE
    INVENTORY,
    INVENTORY_ITEM,
    STORAGE,
    MATERIAL_MOVEMENT,
    PRODUCT,
    GOODS,
    SUPPLY,
    OUTBOUND_DELIVERY,
    INBOUND_DELIVERY,
    SHELF,
    BAR_CODE,

    // LOGISTIKA
    SALES_ORDER,
    DELIVERY_ITEM,
    DRIVER,
    LOGISTICS_PROVIDER,
    VEHICLE,
    ROUTE,
    SHIPMENT,
    TRANSPORT_ORDER,

    // MATERIJALI
    MATERIAL,
    BILL_OF_MATERIAL,
    MATERIAL_REQUEST,
    MATERIAL_REQUIREMENT,
    MATERIAL_TRANSACTION,
    RAW_MATERIAL,

    // PLANIRANJE PROIZVODNJE
    CAPACITY_PLANNING,
    CONFIRMATION_DOCUMENT,
    WORK_CENTER,
    TRACKING_INFO,
    STOCK_TRANSFER,
    STOCK_ITEM_TRANSFER,
    PRODUCTION_ORDER,
    SHIFT,
    SHIFT_REPORT,
    SHIFT_PLANNING,
    REPORT,

    // RACUNOVODSTVO
    ACCOUNT,
    BALANCE_SHEET,
    JOURNAL_ENTRY,
    JOURNAL_ITEM,
    LEDGER_ENTRY,
    INVOICE,
    FISCAL_YEAR,
    FISCAL_QUARTER,
    INCOME_STATEMENT,
    PAYMENT,
    TRANSACTION,
    TAX,

    // KONTROLA KVALITETA
    INSPECTION,
    INSPECTION_DEFECT,
    DEFECT,
    BATCH,
    QUALITY_CHECK,
    QUALITY_STANDARD,
    TEST_MEASUREMENT,
    
    //PRODAJA & DISTRIBUCIJA
    PROCUREMENT,
    SALES,
    SUPPLY_ITEM,
    VENDOR,

    // SISTEMSKI ENTITETI (globalni)
    USER,
    ROLE,
    LANGUAGE,
    PERMISSION,
    OPTION,
    LOCALIZED_OPTION,
    SECURITY_SETTING,
    SYSTEM_STATE,
    SYSTEM_SETTING,
    HELP,
    GOTO,
    FILE_OPT,
    EDIT_OPT,
    EMAIL_SETTING
}
