package com.jovan.erp_v1.util;


/**
 *Klasa za uloge namenjena za kontrolere
 */
public class RoleGroups {

	public static final String DRIVER_FULL_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT')";

	public static final String DRIVER_READ_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT'," +
	        "'INVENTORY_MANAGER','SECURITY_AUDITOR','STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String FULL_DELIVERY_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT')";

	public static final String READ_DELIVERY_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','SALES','PROCUREMENT'," +
	        "'STORAGE_EMPLOYEE','AUDITOR','SECURITY_AUDITOR','MANAGER'," +
	        "'INVENTORY_MANAGER','QUALITY_MANAGER','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String CONFIRMATION_DOCUMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','SALES','PROCUREMENT')";
	
	public static final String CONFIRMATION_DOCUMENT_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','SALES','PROCUREMENT'"
    		+ ",'STORAGE_EMPLOYEE','AUDITOR','SECURITY_AUDITOR','MANAGER','INVENTORY_MANAGER','QUALITY_MANAGER','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String CAPACITY_PLANNING_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER')";
	
	public static final String CAPACITY_PLANNING_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','SECURITY_AUDITOR','STORAGE_EMPLOYEE','STORAGE_FOREMAN','QUALITY_MANAGER')";
	
	public static final String BUYER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT')";
	
	public static final String BUYER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT','AUDITOR','SECURITY_AUDITOR','INVENTORY_MANAGER')";
	
	public static final String BILL_OF_MATERIAL_FULL_ACCESS = "hasAnyRole('ADMIN', 'SUPER_ADMIN', 'PRODUCTION_PLANNER', 'QUALITY_MANAGER')";
	
	public static final String BILL_OF_MATERIAL_READ_ACCESS = "hasAnyRole('ADMIN', 'SUPER_ADMIN', 'PRODUCTION_PLANNER', 'QUALITY_MANAGER','INVENTORY_MANAGER')";
	
	public static final String BALANCE_SHEET_FULL_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT')";
	
	public static final String BALANCE_SHEET_READ_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT','AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String AUDIT_LOG_FULL_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','SECURITY_AUDITOR')";
	
	public static final String AUDIT_LOG_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SECURITY_AUDITOR','QUALITY_MANAGER','ACCOUNTANT')";
	
	public static final String ACCOUNT_FULL_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT')";
	
	public static final String ACCOUNT_READ_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT','AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String EVENT_LOG_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','AUDITOR','SECURITY_AUDITOR','QUALITY_MANAGER')";

	public static final String EVENT_LOG_READ_ACCESS = "hasAnyRole('FINANCIAL_MANAGER','INVENTORY_MANAGER','MANAGER','ACCOUNTANT')";
	
	public static final String FISCAL_QUARTER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER')";
	
	public static final String FISCAL_QUARTER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String FISCAL_YEAR_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER')";
	
	public static final String FISCAL_YEAR_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String GOODS_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT','PRODUCTION_PLANNER')";
	
	public static final String GOODS_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','PRODUCTION_PLANNER','INVENTORY_MANAGER','QUALITY_MANAGER',"
			+ "STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String INBOUND_DELIVERY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER',"
			+ "'STORAGE_FOREMAN','STORAGE_EMPLOYEE','PROCUREMENT')";
	
	public static final String INBOUND_DELIVERY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','PRODUCTION_PLANNER','INVENTORY_MANAGER','STORAGE_FOREMAN',"
			+ "'STORAGE_EMPLOYEE','QUALITY_MANAGER','SECURITY_AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String OUTBOUND_DELIVERY_FULL_ACCESS =
			"hasAnyRole('SUPERADMIN','ADMIN','SALES','PRODUCTION_PLANNER','INVENTORY_MANAGER','STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String OUTBOUND_DELIVERY_READ_ACCESS =
			"hasAnyRole('SUPERADMIN','ADMIN','SALES','PRODUCTION_PLANNER','INVENTORY_MANAGER','STORAGE_FOREMAN','STORAGE_EMPLOYEE','QUALITY_MANAGER','SECURITY_AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String INCOME_STATEMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN,'ACCOUNTANT','FINANCIAL_MANAGER')";
	
	public static final String INCOME_STATEMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String INVENTORY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER','INVENTORY_APPROVER')";
	
	public static final String INVENTORY_EDIT_ACCESS = "hasAnyRole('STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER')";
	
	public static final String INVENTORY_READ_ACCESS ="hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE',"
			+ "'INVENTORY_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER','SECURITY_AUDITOR')";
	
	public static final String INVENTORY_APPROVE_ACCESS ="hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_APPROVER')";
	
	public static final String INVENTORY_ITEMS_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER')";

	public static final String INVENTORY_ITEMS_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER','QUALITY_MANAGER','SECURITY_AUDITOR')";

	public static final String INVOICE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','SALES','FINANCIAL_MANAGER')";
	
	public static final String INVOICE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SECURITY_AUDITOR','AUDITOR','PROCUREMENT','INVENTORY_MANAGER','CUSTOMER_SERVICE')";
	
	public static final String ITEM_SALES_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES')";
	
	public static final String ITEM_SALES_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','SECURITY_AUDITOR','AUDITOR','PROCUREMENT','INVENTORY_MANAGER',"
			+ "FINANCIAL_MANAGER)";
	
	public static final String JOURNAL_ENTRY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String JOURNAL_ENTRY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String JOURNAL_ITEM_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String JOURNAL_ITEM_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String LEDGER_ENTRY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String LEDGER_ENTRY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String LOCALIZED_OPTION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String LOGISTICS_PROVIDER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','STORAGE_FOREMAN','PROCUREMENT')";
	
	public static final String LOGISTICS_PROVIDER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','LOGISTICS_MANAGER','STORAGE_FOREMAN','SALES','CUSTOMER_SERVICE','AUDITOR','SECURITY_AUDITOR','INVENTORY_MANAGER')";
}
