package com.jovan.erp_v1.util;


/**
 *Klasa za uloge namenjena za kontrolere
 */
public class RoleGroups {
	
	public static final String HELP_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";

	public static final String BAR_CODE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SECURITY_AUDITOR','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER')";
	
	public static final String BAR_CODE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SECURITY_AUDITOR','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER')";
	
	public static final String DRIVER_FULL_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT')";

	public static final String DRIVER_READ_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT'," +
	        "'INVENTORY_MANAGER','SECURITY_AUDITOR','STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String FULL_DELIVERY_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT')";

	public static final String READ_DELIVERY_ACCESS =
	        "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','SALES','PROCUREMENT'," +
	        "'STORAGE_EMPLOYEE','AUDITOR','SECURITY_AUDITOR','MANAGER'," +
	        "'INVENTORY_MANAGER','QUALITY_MANAGER','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String CONFIRMATION_DOCUMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','SALES','PROCUREMENT')";
	
	public static final String CONFIRMATION_DOCUMENT_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','SALES','PROCUREMENT'"
    		+ ",'STORAGE_EMPLOYEE','AUDITOR','SECURITY_AUDITOR','MANAGER','INVENTORY_MANAGER','QUALITY_MANAGER','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String CAPACITY_PLANNING_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER')";
	
	public static final String CAPACITY_PLANNING_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','SECURITY_AUDITOR','STORAGE_EMPLOYEE','STORAGE_FOREMAN','QUALITY_MANAGER')";
	
	public static final String BUYER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT')";
	
	public static final String BUYER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT','AUDITOR','SECURITY_AUDITOR','INVENTORY_MANAGER')";
	
	public static final String BILL_OF_MATERIAL_FULL_ACCESS = "hasAnyRole('ADMIN', 'SUPER_ADMIN', 'PRODUCTION_PLANNER', 'QUALITY_MANAGER')";
	
	public static final String BILL_OF_MATERIAL_READ_ACCESS = "hasAnyRole('ADMIN', 'SUPER_ADMIN', 'PRODUCTION_PLANNER', 'QUALITY_MANAGER','INVENTORY_MANAGER')";
	
	public static final String BALANCE_SHEET_FULL_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT')";
	
	public static final String BALANCE_SHEET_READ_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT','AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String AUDIT_LOG_FULL_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','SECURITY_AUDITOR')";
	
	public static final String AUDIT_LOG_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SECURITY_AUDITOR','QUALITY_MANAGER','ACCOUNTANT')";
	
	public static final String ACCOUNT_FULL_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT')";
	
	public static final String ACCOUNT_READ_ACCESS = "hasAnyRole('ADMIN','SUPERADMIN','ACCOUNTANT','AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String EVENT_LOG_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','AUDITOR','SECURITY_AUDITOR','QUALITY_MANAGER')";

	public static final String EVENT_LOG_READ_ACCESS = "hasAnyRole('FINANCIAL_MANAGER','INVENTORY_MANAGER','MANAGER','ACCOUNTANT')";
	
	public static final String FISCAL_QUARTER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER')";
	
	public static final String FISCAL_QUARTER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String FISCAL_YEAR_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER')";
	
	public static final String FISCAL_YEAR_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String GOODS_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','PROCUREMENT','PRODUCTION_PLANNER')";
	
	public static final String GOODS_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','PRODUCTION_PLANNER','INVENTORY_MANAGER','QUALITY_MANAGER',"
			+ "STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String INBOUND_DELIVERY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER',"
			+ "'STORAGE_FOREMAN','STORAGE_EMPLOYEE','PROCUREMENT')";
	
	public static final String INBOUND_DELIVERY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','PRODUCTION_PLANNER','INVENTORY_MANAGER','STORAGE_FOREMAN',"
			+ "'STORAGE_EMPLOYEE','QUALITY_MANAGER','SECURITY_AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String OUTBOUND_DELIVERY_FULL_ACCESS =
			"hasAnyRole('SUPERADMIN','ADMIN','SALES','PRODUCTION_PLANNER','INVENTORY_MANAGER','STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String OUTBOUND_DELIVERY_READ_ACCESS =
			"hasAnyRole('SUPERADMIN','ADMIN','SALES','PRODUCTION_PLANNER','INVENTORY_MANAGER','STORAGE_FOREMAN','STORAGE_EMPLOYEE','QUALITY_MANAGER','SECURITY_AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String INCOME_STATEMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN,'ACCOUNTANT','FINANCIAL_MANAGER')";
	
	public static final String INCOME_STATEMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String INVENTORY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER','INVENTORY_APPROVER')";
	
	public static final String INVENTORY_EDIT_ACCESS = "hasAnyRole('STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER')";
	
	public static final String INVENTORY_READ_ACCESS ="hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE',"
			+ "'INVENTORY_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER','SECURITY_AUDITOR')";
	
	public static final String INVENTORY_APPROVE_ACCESS ="hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_APPROVER')";
	
	public static final String INVENTORY_ITEMS_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER')";

	public static final String INVENTORY_ITEMS_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER','QUALITY_MANAGER','SECURITY_AUDITOR')";

	public static final String INVOICE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','SALES','FINANCIAL_MANAGER')";
	
	public static final String INVOICE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SECURITY_AUDITOR','AUDITOR','PROCUREMENT','INVENTORY_MANAGER','CUSTOMER_SERVICE')";
	
	public static final String ITEM_SALES_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES')";
	
	public static final String ITEM_SALES_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','SECURITY_AUDITOR','AUDITOR','PROCUREMENT','INVENTORY_MANAGER',"
			+ "FINANCIAL_MANAGER)";
	
	public static final String JOURNAL_ENTRY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String JOURNAL_ENTRY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String JOURNAL_ITEM_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String JOURNAL_ITEM_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String LEDGER_ENTRY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT')";
	
	public static final String LEDGER_ENTRY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','FINANCIAL_MANAGER','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String LOCALIZED_OPTION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String LOGISTICS_PROVIDER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','STORAGE_FOREMAN','PROCUREMENT')";
	
	public static final String LOGISTICS_PROVIDER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','LOGISTICS_MANAGER','STORAGE_FOREMAN','SALES','CUSTOMER_SERVICE',"
			+ "'AUDITOR','SECURITY_AUDITOR','INVENTORY_MANAGER')";
	
	public static final String MATERIAL_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT')";
	
	public static final String MATERIAL_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT','INVENTORY_MANAGER',"
			+ "'QUALITY_MANAGER','STORAGE_FOREMAN','STORAGE_EMPLOYEE')";
	
	public static final String MATERIAL_MOVEMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT','STORAGE_FOREMAN')";
	
	public static final String MATERIAL_MOVEMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER',"
			+ "'QUALITY_MANAGER','STORAGE_FOREMAN','STORAGE_EMPLOYEE','PROCUREMENT')";
	
	public static final String MATERIAL_REQUEST_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT','STORAGE_FOREMAN','LOGISTICS_MANAGER','INVENTORY_MANAGER')";
	
	public static final String MATERIAL_REQUEST_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT','STORAGE_FOREMAN','LOGISTICS_MANAGER',"
			+ "'QUALITY_MANAGER','STORAGE_EMPLOYEE','INVENTORY_MANAGER')";
	
	public static final String MATERIAL_REQUIREMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT','STORAGE_FOREMAN','LOGISTICS_MANAGER','INVENTORY_MANAGER')";
	
	public static final String MATERIAL_REQUIREMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','PROCUREMENT','STORAGE_FOREMAN','LOGISTICS_MANAGER','INVENTORY_MANAGER',"
			+ "'QUALITY_MANAGER','STORAGE_EMPLOYEE')";
	
	public static final String MATERIAL_TRANSACTION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','STORAGE_FOREMAN','INVENTORY_MANAGER','PROCUREMENT')";
	
	public static final String MATERIAL_TRANSACTION_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','STORAGE_FOREMAN','INVENTORY_MANAGER',"
			+ "'PROCUREMENT','QUALITY_MANAGER','STORAGE_EMPLOYEE')";
	
	public static final String OPTION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String PAYMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','SALES')";
	
	public static final String PAYMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','SALES','PROCUREMENT','SECURITY_AUDITOR','AUDITOR','FINANCIAL_MANAGER','CUSTOMER_SERVICE')";
	
	public static final String PERMISSION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String PROCUREMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','SALES','ACCOUNTANT','INVENTORY_MANAGER')";
	
	public static final String PROCUREMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','SALES','ACCOUNTANT','INVENTORY_MANAGER',"
			+ "'SECURITY_AUDITOR','AUDITOR','FINANCIAL_MANAGER','STORAGE_FOREMAN')";
	
	public static final String PRODUCT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','SALES','QUALITY_MANAGER','PROCUREMENT')";
	
	public static final String PRODUCT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','SALES','QUALITY_MANAGER','PROCUREMENT','STORAGE_EMPLOYEE',"
			+ "'STORAGE_FOREMAN','ACCOUNTANT')";
	
	public static final String PRODUCTION_ORDER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','LOGISTICS_MANAGER','PROCUREMENT')";
	
	public static final String PRODUCTION_ORDER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','LOGISTICS_MANAGER','QUALITY_MANAGER',"
			+ "'STORAGE_EMPLOYEE','STORAGE_FOREMAN','PROCUREMENT','ACCOUNTANT','FINANCIAL_MANAGER')";
	
	public static final String RAW_MATERIAL_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','QUALITY_MANAGER','PROCUREMENT')";
	
	public static final String RAW_MATERIAL_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_PLANNER','INVENTORY_MANAGER','SALES','QUALITY_MANAGER','PROCUREMENT',"
			+ "'STORAGE_EMPLOYEE','STORAGE_FOREMAN','ACCOUNTANT')";
	
	public static final String REPORT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','ACCOUNTANT','PROCUREMENT','LOGISTICS_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER')";
	
	public static final String REPORT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','ACCOUNTANT','PROCUREMENT','LOGISTICS_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER',"
			+ "'SALES','STORAGE_EMPLOYEE','INVENTORY_MANAGER','AUDITOR','SECURITY_AUDITOR','FINANCIAL_MANAGER'";
	
	public static final String ROLE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String ROUTE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','DISPATCHER','PROCUREMENT')";
	
	public static final String ROUTE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','AUDITOR','SECURITY_AUDITOR','ACCOUNTANT',"
			+ "'STORAGE_FOREMAN','STORAGE_EMPLOYEE','INVENTORY_MANAGER','SALES')";
	
	public static final String SALES_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','ACCOUNTANT','FINANCIAL_MANAGER')";
	
	public static final String SALES_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','ACCOUNTANT','FINANCIAL_MANAGER','AUDITOR','SECURITY_AUDITOR',"
			+ "'INVENTORY_MANAGER','LOGISTICS_MANAGER','PROCUREMENT','STORAGE_FOREMAN')";
	
	public static final String SECURITY_SETTING_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String SALES_ORDER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','ACCOUNTANT','FINANCIAL_MANAGER','PROCUREMENT','SALES_MANAGER','LOGISTICS_MANAGER')";
	
	public static final String SALES_ORDER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','SALES','ACCOUNTANT','FINANCIAL_MANAGER','PROCUREMENT','SALES_MANAGER','LOGISTICS_MANAGER',"
			+ "'AUDITOR','SECURITY_AUDITOR','STORAGE_FOREMAN','QUALITY_MANAGER')";
	
	public static final String SHELF_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','STORAGE_FOREMAN','INVENTORY_APPROVER','LOGISTICS_MANAGER')";
	
	public static final String SHELF_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','STORAGE_FOREMAN','INVENTORY_APPROVER','LOGISTICS_MANAGER',"
			+ "'PRODUCTION_PLANNER','QUALITY_MANAGER','AUDITOR')";
	
	public static final String SHIFT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','HR_MANAGER')";
	
	public static final String SHIFT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','HR_MANAGER','PRODUCTION_PLANNER','AUDITOR')";
	
	public static final String SHIFT_PLANNING_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','HR_MANAGER')";

	public static final String SHIFT_PLANNING_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','HR_MANAGER','PRODUCTION_PLANNER','AUDITOR')";
	
	public static final String SHIFT_REPORT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','HR_MANAGER')";
	
	public static final String SHIFT_REPORT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','STORAGE_FOREMAN','HR_MANAGER','AUDITOR','QUALITY_MANAGER')";
	
	public static final String SHIPMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','STORAGE_FOREMAN')";
	
	public static final String SHIPMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','STORAGE_FOREMAN','DISPATCHER',"
			+ "'CUSTOMER_SERVICE','AUDITOR')";
	
	public static final String STOCK_TRANSFER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','PRODUCTION_PLANNER','LOGISTICS_MANAGER','TRANSPORT_PLANNER')";
	
	public static final String STOCK_TRANSFER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','PRODUCTION_PLANNER','LOGISTICS_MANAGER','TRANSPORT_PLANNER',"
			+ "'STORAGE_FOREMAN','SECURITY_AUDITOR','AUDITOR','ACCOUNTANT','QUALITY_MANAGER','STORAGE_EMPLOYEE','PROCUREMENT')";
	
	public static final String STOCK_TRANSFER_ITEM_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','PRODUCTION_PLANNER','LOGISTICS_MANAGER','TRANSPORT_PLANNER')";
	
	public static final String STOCK_TRANSFER_ITEM_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','PRODUCTION_PLANNER','LOGISTICS_MANAGER','TRANSPORT_PLANNER',"
			+ "'STORAGE_FOREMAN','SECURITY_AUDITOR','AUDITOR','ACCOUNTANT','QUALITY_MANAGER','STORAGE_EMPLOYEE','PROCUREMENT')";
	
	public static final String STORAGE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','STORAGE_FOREMAN')";

	public static final String STORAGE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','INVENTORY_MANAGER','STORAGE_FOREMAN','PRODUCTION_PLANNER','QUALITY_MANAGER','AUDITOR')";
	
	public static final String SUPPLY_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','ACCOUNTANT')";
	
	public static final String SUPPLY_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR','INVENTORY_MANAGER',"
			+ "'STORAGE_FOREMAN','QUALITY_MANAGER')";
	
	public static final String SUPPLY_ITEM_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','ACCOUNTANT')";
	
	public static final String SUPPLY_ITEM_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR','INVENTORY_MANAGER')";
	
	public static final String SYSTEM_SETTING_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String SYSTEM_STATE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String TAX_RATE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','SECURITY_AUDITOR')";
	
	public static final String TAX_RATE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','SECURITY_AUDITOR','AUDITOR','FINANCIAL_MANAGER')";
	
	public static final String TRACKING_INFO_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER')";
	
	public static final String TRACKING_INFO_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','DISPATCHER')";
	
	public static final String TRANSPORT_ORDER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','DISPATCHER')";

	public static final String TRANSPORT_ORDER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','DISPATCHER','DRIVER')";
	
	public static final String USER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String VEHICLE_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER')";
	
	public static final String VEHICLE_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','DISPATCHER','DRIVER','MECHANIC')";
	
	public static final String VENDOR_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','ACCOUNTANT')";
	
	public static final String VENDOR_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PROCUREMENT','ACCOUNTANT','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String WORK_CENTER_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_MANAGER','PRODUCTION_PLANNER','MAINTENANCE_MANAGER')";
	
	public static final String WORK_CENTER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_MANAGER','PRODUCTION_PLANNER','MAINTENANCE_MANAGER','AUDITOR','SECURITY_AUDITOR','QUALITY_MANAGER')";
	
	public static final String DEFECT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','INVENTORY_MANAGER','MAINTENANCE_MANAGER')";
	
	public static final String DEFECT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','INVENTORY_MANAGER','MAINTENANCE_MANAGER','PRODUCTION_MANAGER','PRODUCTION_PLANNER','SECURITY_AUDITOR')";
	
	public static final String BATCH_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER','INVENTORY_MANAGER')";
	
	public static final String BATCH_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','PRODUCTION_MANAGER','PRODUCTION_PLANNER','QUALITY_MANAGER','INVENTORY_MANAGER',"
			+ "'MAINTENANCE_MANAGER','SALES_MANAGER','CUSTOMER_SERVICE','REGULATORY_AUDITOR')";
	
	public static final String QUALITY_CHECK_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','PRODUCTION_MANAGER','MAINTENANCE_MANAGER')";
	
	public static final String QUALITY_CHECK_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','PRODUCTION_MANAGER','MAINTENANCE_MANAGER',"
			+ "'INVENTORY_MANAGER','PRODUCTION_PLANNER','SALES_MANAGER','CUSTOMER_SERVICE','REGULATORY_AUDITOR')";
	
	public static final String TEST_MEASUREMENT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN','MAINTENANCE_MANAGER')";
	
	public static final String TEST_MEASUREMENT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN','MAINTENANCE_MANAGER',"
			+ "'INVENTORY_MANAGER','PRODUCTION_MANAGER','REGULATORY_AUDITOR','PRODUCTION_PLANNER','SALES_MANAGER')";
	
	public static final String QUALITY_STANDARD_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER')";
	
	public static final String QUALITY_STANDARD_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN','MAINTENANCE_MANAGER',"
			+ "'PRODUCTION_PLANNER','INVENTORY_MANAGER','REGULATORY_AUDITOR','SALES_MANAGER','PRODUCTION_MANAGER')";
	
	public static final String INSPECTION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN')";
	
	public static final String INSPECTION_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN','INVENTORY_MANAGER','REGULATORY_AUDITOR',"
			+ "'PRODUCTION_PLANNER','PRODUCTION_MANAGER','SALES_MANAGER','MAINTENANCE_MANAGER')";
	
	public static final String INSPECTION_DEFECT_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN')";
	
	public static final String INSPECTION_DEFECT_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','QUALITY_MANAGER','QUALITY_INSPECTOR','QUALITY_TECHNICIAN','INVENTORY_MANAGER',"
			+ "'PRODUCTION_PLANNER','PRODUCTION_MANAGER','SALES_MANAGER','MAINTENANCE_MANAGER','SECURITY_AUDITOR','REGULATORY_AUDITOR','SUPPLY_CHAIN_MANAGER')";
	
	public static final String TRANSACTION_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER')";
	
	public static final String TRANSACTION_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String TRANSACTION_AUDIT_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','ACCOUNTANT','FINANCIAL_MANAGER','AUDITOR','SECURITY_AUDITOR')";
	
	public static final String GOTO_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN')";
	
	public static final String TRIP_FULL_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER')";
	
	public static final String TRIP_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','LOGISTICS_MANAGER','TRANSPORT_PLANNER','DISPATCHER')";
	
	public static final String TRIP_DRIVER_READ_ACCESS = "hasAnyRole('SUPERADMIN','ADMIN','DRIVER'";
}
